In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression, Lars, ElasticNet, Lasso, Ridge, BayesianRidge
#pd.set_option('display.float_format', lambda x: "{:,.2f}".format(x))

In [2]:
red=pd.read_csv('./csv/wine/winequality-red.csv',sep=";")
white=pd.read_csv('./csv/wine/winequality-white.csv',sep=";")

In [3]:
dc_scores_red = {}
dc_scores_white = {}

In [4]:
red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [6]:
white.shape

(4898, 12)

In [7]:
red.shape

(1599, 12)

In [8]:
((red.isna().sum()*100)/red.shape[0]).to_frame()

0
fixed acidity         0.0
volatile acidity      0.0
citric acid           0.0
residual sugar        0.0
chlorides             0.0
free sulfur dioxide   0.0
total sulfur dioxide  0.0
density               0.0
pH                    0.0
sulphates             0.0
alcohol               0.0
quality               0.0

In [9]:
((white.isna().sum()*100)/white.shape[0]).to_frame()

0
fixed acidity         0.0
volatile acidity      0.0
citric acid           0.0
residual sugar        0.0
chlorides             0.0
free sulfur dioxide   0.0
total sulfur dioxide  0.0
density               0.0
pH                    0.0
sulphates             0.0
alcohol               0.0
quality               0.0

In [10]:
tgt = "quality"
ls_pred = [x for x in white.columns if x not in [tgt]]

X_white = white[ls_pred]
y_white = white[tgt]
X_red = white[ls_pred]
y_red = white[tgt]

## 1) Regresión Lineal

### RED WHINE

In [11]:
linreg = LinearRegression()

In [12]:
linreg.fit(X_red, y_red)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
ls_res = cross_val_score(estimator = linreg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")

In [14]:
np.mean(ls_res), np.std(ls_res)

(0.2320825168385873, 0.0603907896686925)

In [15]:
linreg.intercept_

150.19284248121158

In [16]:
linreg.coef_

array([ 6.55199614e-02, -1.86317709e+00,  2.20902007e-02,  8.14828026e-02,
       -2.47276537e-01,  3.73276519e-03, -2.85747419e-04, -1.50284181e+02,
        6.86343742e-01,  6.31476473e-01,  1.93475697e-01])

In [17]:
dc_scores_red.update({str(linreg).split("(")[0]: np.mean(ls_res)})

In [18]:
dc_scores_red

{'LinearRegression': 0.2320825168385873}

### WHITE WINE

In [19]:
linreg = LinearRegression()

In [20]:
linreg.fit(X_white, y_white)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
ls_res = cross_val_score(estimator = linreg, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")

In [22]:
np.mean(ls_res), np.std(ls_res)

(0.2320825168385873, 0.0603907896686925)

In [23]:
linreg.intercept_

150.19284248121158

In [24]:
linreg.coef_

array([ 6.55199614e-02, -1.86317709e+00,  2.20902007e-02,  8.14828026e-02,
       -2.47276537e-01,  3.73276519e-03, -2.85747419e-04, -1.50284181e+02,
        6.86343742e-01,  6.31476473e-01,  1.93475697e-01])

In [25]:
dc_scores_white.update({str(linreg).split("(")[0]: np.mean(ls_res)})

In [26]:
dc_scores_white

{'LinearRegression': 0.2320825168385873}

## 2) Regresión LARS

### RED WINE

In [27]:
larsreg = Lars()

In [28]:
larsreg.fit(X_red, y_red)

Lars(copy_X=True, eps=2.220446049250313e-16, fit_intercept=True, fit_path=True,
     n_nonzero_coefs=500, normalize=True, positive=False, precompute='auto',
     verbose=False)

In [29]:
ls_res = cross_val_score(estimator = larsreg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")

In [30]:
np.mean(ls_res), np.std(ls_res)

(0.07493476069027624, 0.22869832269161847)

In [31]:
larsreg.intercept_

179.60233652109176

In [32]:
larsreg.coef_

array([ 9.85944908e-02, -1.85327774e+00,  1.76402388e-02,  9.34934317e-02,
       -1.04191227e-01,  3.83788581e-03, -3.17500465e-04, -1.80320348e+02,
        8.25111207e-01,  6.89669301e-01,  1.61683376e-01])

In [33]:
dc_scores_red.update({str(larsreg).split("(")[0]: np.mean(ls_res)})

In [34]:
dc_scores_red

{'LinearRegression': 0.2320825168385873, 'Lars': 0.07493476069027624}

### WHITE WINE

In [35]:
larsreg = Lars()

In [36]:
larsreg.fit(X_white, y_white)

Lars(copy_X=True, eps=2.220446049250313e-16, fit_intercept=True, fit_path=True,
     n_nonzero_coefs=500, normalize=True, positive=False, precompute='auto',
     verbose=False)

In [37]:
ls_res = cross_val_score(estimator = larsreg, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")

In [38]:
np.mean(ls_res), np.std(ls_res)

(0.07493476069027624, 0.22869832269161847)

In [39]:
larsreg.intercept_

179.60233652109176

In [40]:
larsreg.coef_

array([ 9.85944908e-02, -1.85327774e+00,  1.76402388e-02,  9.34934317e-02,
       -1.04191227e-01,  3.83788581e-03, -3.17500465e-04, -1.80320348e+02,
        8.25111207e-01,  6.89669301e-01,  1.61683376e-01])

In [41]:
dc_scores_white.update({str(larsreg).split("(")[0]: np.mean(ls_res)})

In [42]:
dc_scores_white

{'LinearRegression': 0.2320825168385873, 'Lars': 0.07493476069027624}

## 3) Regresión Cresta

### RED WINE

In [43]:
ridgereg = Ridge(alpha=1)

In [44]:
ridgereg.fit(X_red, y_red)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [45]:
ls_res = cross_val_score(estimator = ridgereg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")

In [46]:
np.mean(ls_res), np.std(ls_res)

(0.22912117432938742, 0.06871256232786656)

In [47]:
ridgereg.intercept_

2.242940872099817

In [48]:
ridgereg.coef_

array([-4.94096321e-02, -1.92307971e+00, -2.89752960e-02,  2.58078161e-02,
       -6.45888825e-01,  4.82834129e-03, -9.06941267e-04, -2.36337965e-01,
        1.70656705e-01,  4.14170445e-01,  3.63885782e-01])

In [49]:
dc_scores_red.update({str(ridgereg).split("(")[0]: np.mean(ls_res)})

In [50]:
dc_scores_red

{'LinearRegression': 0.2320825168385873,
 'Lars': 0.07493476069027624,
 'Ridge': 0.22912117432938742}

### WHITE WHINE

In [51]:
ridgereg = Ridge(alpha=1)

In [52]:
ridgereg.fit(X_white, y_white)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [53]:
ls_res = cross_val_score(estimator = ridgereg, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")

In [54]:
np.mean(ls_res), np.std(ls_res)

(0.22912117432938742, 0.06871256232786656)

In [55]:
ridgereg.intercept_

2.242940872099817

In [56]:
ridgereg.coef_

array([-4.94096321e-02, -1.92307971e+00, -2.89752960e-02,  2.58078161e-02,
       -6.45888825e-01,  4.82834129e-03, -9.06941267e-04, -2.36337965e-01,
        1.70656705e-01,  4.14170445e-01,  3.63885782e-01])

In [57]:
dc_scores_white.update({str(ridgereg).split("(")[0]: np.mean(ls_res)})

In [58]:
dc_scores_white

{'LinearRegression': 0.2320825168385873,
 'Lars': 0.07493476069027624,
 'Ridge': 0.22912117432938742}

### Variación de alphas

In [59]:
ridgereg = Ridge()
ridgereg.fit(X_red, y_red)
ls_res = cross_val_score(estimator = ridgereg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")
print(np.mean(ls_res))
ident=1
val=np.mean(ls_res)
for i in range(2,20):
    ridgereg = Ridge(alpha=i)
    ridgereg.fit(X_red, y_red)
    ls_res = cross_val_score(estimator = ridgereg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")
    print(np.mean(ls_res))
    if(val<np.mean(ls_res)):
        ident=i
        val=np.mean(ls_res)

0.22912117432938742
0.2289820460646679
0.22879222094337603
0.22855903785069584
0.2282889376700423
0.22798768237285377
0.2276603913439315
0.22731155476829626
0.22694507536548977
0.22656432645727922
0.2261722141983125
0.2257712373718878
0.22536354187390337
0.2249509689814538
0.22453509745632008
0.2241172799531214
0.22369867435335516
0.22328027066819067
0.22286291411527737


In [60]:
ridgereg = Ridge()
ridgereg.fit(X_white, y_white)
ls_res = cross_val_score(estimator = ridgereg, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")
print(np.mean(ls_res))
ident=1
val=np.mean(ls_res)
for i in range(2,20):
    ridgereg = Ridge(alpha=i)
    ridgereg.fit(X_white, y_white)
    ls_res = cross_val_score(estimator = ridgereg, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")
    print(np.mean(ls_res))
    if(val<np.mean(ls_res)):
        ident=i
        val=np.mean(ls_res)

0.22912117432938742
0.2289820460646679
0.22879222094337603
0.22855903785069584
0.2282889376700423
0.22798768237285377
0.2276603913439315
0.22731155476829626
0.22694507536548977
0.22656432645727922
0.2261722141983125
0.2257712373718878
0.22536354187390337
0.2249509689814538
0.22453509745632008
0.2241172799531214
0.22369867435335516
0.22328027066819067
0.22286291411527737


## 4) Regresión Lasso

### RED WINE

In [61]:
lassreg = Lasso()

In [62]:
lassreg.fit(X_red, y_red)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [63]:
ls_res = cross_val_score(estimator = lassreg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")

In [64]:
np.mean(ls_res), np.std(ls_res)

(0.017703674685833753, 0.01747040078031327)

In [65]:
lassreg.intercept_

6.301726183589768

In [66]:
lassreg.coef_

array([-0.        , -0.        ,  0.        , -0.        , -0.        ,
        0.00276196, -0.00376795, -0.        ,  0.        ,  0.        ,
        0.        ])

In [67]:
dc_scores_red.update({str(lassreg).split("(")[0]: np.mean(ls_res)})

### WHITE WINE

In [68]:
lassreg = Lasso()

In [69]:
lassreg.fit(X_white, y_white)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [70]:
ls_res = cross_val_score(estimator = lassreg, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")

In [71]:
np.mean(ls_res), np.std(ls_res)

(0.017703674685833753, 0.01747040078031327)

In [72]:
lassreg.intercept_

6.301726183589768

In [73]:
lassreg.coef_

array([-0.        , -0.        ,  0.        , -0.        , -0.        ,
        0.00276196, -0.00376795, -0.        ,  0.        ,  0.        ,
        0.        ])

In [74]:
dc_scores_white.update({str(lassreg).split("(")[0]: np.mean(ls_res)})

In [75]:
dc_scores_white

{'LinearRegression': 0.2320825168385873,
 'Lars': 0.07493476069027624,
 'Ridge': 0.22912117432938742,
 'Lasso': 0.017703674685833753}

In [78]:
lassreg = Lasso()
lassreg.fit(X_red, y_red)
ls_res = cross_val_score(estimator = lassreg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")
print(np.mean(ls_res))
ident=1
val=np.mean(ls_res)
for i in range(2,20):
    lassreg = Lasso(alpha=i)
    lassreg.fit(X_red, y_red)
    ls_res = cross_val_score(estimator = lassreg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")
    print(np.mean(ls_res))
    if(val<np.mean(ls_res)):
        ident=i
        val=np.mean(ls_res)

0.017703674685833753
0.0063971094688958785
0.002463892346821428
-0.0029585905131047363
-0.009870339110882559
-0.016097822977968385
-0.020888518033933934
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077


## 5) Red elástica

### RED WINE

In [79]:
elasnet = ElasticNet()

In [80]:
elasnet.fit(X_red, y_red)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [81]:
ls_res = cross_val_score(estimator = elasnet, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")

In [82]:
np.mean(ls_res), np.std(ls_res)

(0.026555146227103532, 0.01094047255265413)

In [83]:
elasnet.intercept_

6.335616808267631

In [84]:
elasnet.coef_

array([-0.        , -0.        ,  0.        , -0.        , -0.        ,
        0.00621026, -0.00489286, -0.        ,  0.        ,  0.        ,
        0.        ])

In [85]:
dc_scores_red.update({str(elasnet).split("(")[0]: np.mean(ls_res)})

### WHITE WINE

In [86]:
elasnet = ElasticNet()

In [89]:
elasnet.fit(X_white, y_white)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [90]:
ls_res = cross_val_score(estimator = elasnet, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")

In [91]:
np.mean(ls_res), np.std(ls_res)

(0.026555146227103532, 0.01094047255265413)

In [92]:
elasnet.intercept_

6.335616808267631

In [93]:
elasnet.coef_

array([-0.        , -0.        ,  0.        , -0.        , -0.        ,
        0.00621026, -0.00489286, -0.        ,  0.        ,  0.        ,
        0.        ])

In [95]:
dc_scores_white.update({str(elasnet).split("(")[0]: np.mean(ls_res)})

In [96]:
dc_scores_white

{'LinearRegression': 0.2320825168385873,
 'Lars': 0.07493476069027624,
 'Ridge': 0.22912117432938742,
 'Lasso': 0.017703674685833753,
 'ElasticNet': 0.026555146227103532}

### VARIACIÓN DE ALPHAS

In [97]:
elasnet = ElasticNet()
elasnet.fit(X_red, y_red)
ls_res = cross_val_score(estimator = elasnet, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")
print(np.mean(ls_res))
ident=1
val=np.mean(ls_res)
for i in range(2,20):
    elasnet = ElasticNet(alpha=i)
    elasnet.fit(X_red, y_red)
    ls_res = cross_val_score(estimator = elasnet, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")
    print(np.mean(ls_res))
    if(val<np.mean(ls_res)):
        ident=i
        val=np.mean(ls_res)

0.026555146227103532
0.017647626219345708
0.008256851048672298
0.006384364226175943
0.004598664644396094
0.002441071616871071
-8.779260441793557e-05
-0.002987306808857171
-0.00625685082526195
-0.00989580551994304
-0.013580904333104021
-0.016113239857635825
-0.018932864663452703
-0.02088982922463395
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077


In [98]:
elasnet = ElasticNet()
elasnet.fit(X_white, y_white)
ls_res = cross_val_score(estimator = elasnet, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")
print(np.mean(ls_res))
ident=1
val=np.mean(ls_res)
for i in range(2,20):
    elasnet = ElasticNet(alpha=i)
    elasnet.fit(X_white, y_white)
    ls_res = cross_val_score(estimator = elasnet, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")
    print(np.mean(ls_res))
    if(val<np.mean(ls_res)):
        ident=i
        val=np.mean(ls_res)

0.026555146227103532
0.017647626219345708
0.008256851048672298
0.006384364226175943
0.004598664644396094
0.002441071616871071
-8.779260441793557e-05
-0.002987306808857171
-0.00625685082526195
-0.00989580551994304
-0.013580904333104021
-0.016113239857635825
-0.018932864663452703
-0.02088982922463395
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077
-0.02122376323754077


## 6) Regresión Bayesiana

### RED WINE

In [100]:
bayreg = BayesianRidge()

In [101]:
bayreg.fit(X_red, y_red)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
              fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
              normalize=False, tol=0.001, verbose=False)

In [102]:
ls_res = cross_val_score(estimator = bayreg, X=X_red, y=y_red, cv=4, n_jobs=-1, scoring="r2")

In [103]:
np.mean(ls_res), np.std(ls_res)

(0.22898890640896596, 0.06896684789036629)

In [104]:
bayreg.intercept_

2.19046120101567

In [105]:
bayreg.coef_

array([-4.93338300e-02, -1.91429473e+00, -2.84625366e-02,  2.57926229e-02,
       -6.01526053e-01,  4.84337592e-03, -9.15184376e-04, -1.91423583e-01,
        1.71246298e-01,  4.12852478e-01,  3.64089340e-01])

In [106]:
dc_scores_red.update({str(bayreg).split("(")[0]: np.mean(ls_res)})

### WHITE WINE

In [107]:
bayreg = BayesianRidge()

In [108]:
bayreg.fit(X_white, y_white)

BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, compute_score=False, copy_X=True,
              fit_intercept=True, lambda_1=1e-06, lambda_2=1e-06, n_iter=300,
              normalize=False, tol=0.001, verbose=False)

In [109]:
ls_res = cross_val_score(estimator = bayreg, X=X_white, y=y_white, cv=4, n_jobs=-1, scoring="r2")

In [110]:
np.mean(ls_res), np.std(ls_res)

(0.22898890640896596, 0.06896684789036629)

In [111]:
bayreg.intercept_

2.19046120101567

In [112]:
bayreg.coef_

array([-4.93338300e-02, -1.91429473e+00, -2.84625366e-02,  2.57926229e-02,
       -6.01526053e-01,  4.84337592e-03, -9.15184376e-04, -1.91423583e-01,
        1.71246298e-01,  4.12852478e-01,  3.64089340e-01])

In [113]:
dc_scores_white.update({str(bayreg).split("(")[0]: np.mean(ls_res)})

In [114]:
dc_scores_white

{'LinearRegression': 0.2320825168385873,
 'Lars': 0.07493476069027624,
 'Ridge': 0.22912117432938742,
 'Lasso': 0.017703674685833753,
 'ElasticNet': 0.026555146227103532,
 'BayesianRidge': 0.22898890640896596}

white

In [115]:
white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [135]:
resul = pd.DataFrame(columns=[])
alfas = pd.DataFrame(columns=[])
for model in [linreg, larsreg, ridgereg, lassreg, elasnet, bayreg]:
    resul[str(model).split("(")[0]] = model.coef_
    alfas[str(model).split("(")[0]] = [model.intercept_]

In [136]:
resul["features"] = ls_pred
resul = resul.set_index("features")
alfas["features"] = ["intercepto"]
alfas = alfas.set_index("features")

In [137]:
resul = alfas.append(resul)

In [138]:
resul

LinearRegression        Lars     Ridge     Lasso  \
features                                                                 
intercepto                  150.192842  179.602337  1.920312  5.877909   
fixed acidity                 0.065520    0.098594 -0.047899 -0.000000   
volatile acidity             -1.863177   -1.853278 -1.394149 -0.000000   
citric acid                   0.022090    0.017640  0.026759 -0.000000   
residual sugar                0.081483    0.093493  0.024556 -0.000000   
chlorides                    -0.247277   -0.104191 -0.123094 -0.000000   
free sulfur dioxide           0.003733    0.003838  0.005648  0.000000   
total sulfur dioxide         -0.000286   -0.000318 -0.001283 -0.000000   
density                    -150.284181 -180.320348 -0.013062 -0.000000   
pH                            0.686344    0.825111  0.177452  0.000000   
sulphates                     0.631476    0.689669  0.338640  0.000000   
alcohol                       0.193476    0.161683  0.358846  0.000000   

                      ElasticNet  BayesianRidge  
features                                         
intercepto              5.877909       2.190461  
fixed acidity          -0.000000      -0.049334  
volatile acidity       -0.000000      -1.914295  
citric acid            -0.000000      -0.028463  
residual sugar         -0.000000       0.025793  
chlorides              -0.000000      -0.601526  
free sulfur dioxide     0.000000       0.004843  
total sulfur dioxide   -0.000000      -0.000915  
density                -0.000000      -0.191424  
pH                      0.000000       0.171246  
sulphates               0.000000       0.412852  
alcohol                 0.000000       0.364089

In [141]:
resul.to_excel("practica2/alphas.xlsx")

## R^2 Y PEMA

In [143]:
def PEMA(data,obj,yhat):
    df=data.copy()
    df["y_hat"]=yhat
    return ((df[obj]-df["y_hat"])/df[obj]).sum()

In [144]:
pema=[]
r2=[]
for model in [linreg, larsreg, ridgereg, lassreg, elasnet, bayreg]:
    pema.append(PEMA(white,tgt,model.predict(X=white[ls_pred])))
    r2.append(r2_score(y_true=white[tgt],y_pred=model.predict(X=white[ls_pred])))
    

In [145]:
pema_r_white = pd.DataFrame(columns=[])

In [146]:
models=["linreg", "larsreg", "ridgereg", "lassreg", "elasnet", "bayreg"]
pema_r_white["pema"]=pema
pema_r_white["r2"]=r2
pema_r_white["models"]=models

In [147]:
pema_r_white.set_index("models")

pema        r2
models                        
linreg    -84.998741  0.281870
larsreg   -84.587097  0.281397
ridgereg  -88.141118  0.268228
lassreg  -117.589726  0.000000
elasnet  -117.589726  0.000000
bayreg    -86.256327  0.272675

In [148]:
pema_r_white.set_index("models").to_excel("practica2/pema_r_white.xlsx")

In [149]:
pema=[]
r2=[]
for model in [linreg, larsreg, ridgereg, lassreg, elasnet, bayreg]:
    pema.append(PEMA(red,tgt,model.predict(X=red[ls_pred])))
    r2.append(r2_score(y_true=red[tgt],y_pred=model.predict(X=red[ls_pred])))

In [150]:
pema_r_red = pd.DataFrame(columns=[])

In [151]:
models=["linreg", "larsreg", "ridgereg", "lassreg", "elasnet", "bayreg"]
pema_r_red["pema"]=pema
pema_r_red["r2"]=r2
pema_r_red["models"]=models

In [152]:
pema_r_red.set_index("models")

pema        r2
models                        
linreg    191.615050 -0.570968
larsreg   203.267435 -0.667064
ridgereg   42.229105  0.214188
lassreg  -104.390140 -0.089771
elasnet  -104.390140 -0.089771
bayreg     90.547038  0.047299

In [153]:
pema_r_red.set_index("models").to_excel("practica2/pema_r_red.xlsx")